CFLAGS=-Wall -g

clean:
	rm -f helloworld
	rm -f formattedprinting
	rm -f typesofvars
all:
	make --no-print-directory helloworld
	make --no-print-directory formattedprinting
	make --no-print-directory typesofvars
